### PR TITLE
Add article about "using namespace std"

### PR DESCRIPTION
**Pull request by NoHandsMate**

### CODE REVIEW

**Comment by 64** [comment]
Thank you for the PR.

I think some simpler examples would get the point across just as well (absolute beginners may not have come across the syntax for definining your own templated types) - maybe instead use some variable named `count` or `swap`, as is done [here](https://stackoverflow.com/a/27718061/3183526)?

The second example is a bit problematic because the string literal won't convert to a `std::string&` anyway (i.e if `lib_2` did not exist, it would fail to compile). Maybe check https://isocpp.org/wiki/faq/coding-standards#using-namespace-std and the SO thread above for some inspiration on what to say instead.

**Comment by NoHandsMate** [comment]
Thanks for the review, and you are absolutely right. I will adjust this article using the sources that you send.

**Comment by NoHandsMate** [comment]
@64 Let me know if now u like it

**Comment by 64** [comment]
Thanks :+1:

**Pull request merged**
